STEP1. 자동차 경주 개발
ChoisingTeam/playground-euigyu pull request #1
Opened 2020-03-03 14:31 UTC by euigyu

1. Scanner를 활용하여 입력받기 
2. Math 클래스의 randm 메소드를 활용하여 랩덤숫자 입력
3. 2중 for문으로 각 차량 당 시도 횟수를 적용

2020-03-03 14:43 UTC, Oraindrop requested changes
git 연동부터 첫 PR 까지 험난했네요 형님 고생하셨습니다.
일단 main 함수에서 전부 다 하는건 구조적 프로그래밍(절차지향) 에 가까워 보이네요.
클래스-객체를 하나라도 사용하셔서 구현해보셨으면 좋겠습니다.
클래스에 메소드를 만들 때는 최대한 메소드를 짧게 만들어보아요~

2020-03-03 14:43 UTC, Oraindrop commented on src/main/java/io/github/choising/team/Main.java
>  public class Main {
Class Naming 을 항상 의미있는 것으로 가져가봐요.

2020-03-03 14:43 UTC, Oraindrop commented on src/main/java/io/github/choising/team/Main.java
> +        System.out.println("자동차대수는몇대인가요?");
개발 편의로 요구사항을 변경하면 안됩니다. 띄어쓰기 및 출력형식을 준수해주세요.
```
자동차 대수는 몇 대 인가요?
3
시도할 회수는 몇 회 인가요?
5

실행 결과
----
----
-----
```

2020-03-03 14:43 UTC, Oraindrop commented on src/main/java/io/github/choising/team/Main.java
> +        System.out.println("시도할횟수는몇회인가요?");
개발 편의로 요구사항을 변경하면 안됩니다. 띄어쓰기 및 출력형식을 준수해주세요 2

2020-03-03 14:43 UTC, Oraindrop commented on src/main/java/io/github/choising/team/Main.java
> +            System.out.println();
개발 편의로 요구사항을 변경하면 안됩니다. 띄어쓰기 및 출력형식을 준수해주세요 3

2020-03-03 14:43 UTC, Oraindrop commented on src/main/java/io/github/choising/team/Main.java
> +                int randomValue = (int) (Math.random() * 9);
요구사항은 0에서 9까지의 Random 값이었죠.
```
(int) (Math.random() * 9)
```
이렇게 하면 0에서 9까지 나오는게 확실한가요?
제가 볼 때는 9는 영원히 안나올 것 같습니다~

2020-03-04 14:24 UTC, euigyu commented on src/main/java/io/github/choising/team/Main.java
>  public class Main {
클래스 이름을 CarRace로 수정해서 의미를 부여해씀

2020-03-04 14:24 UTC, euigyu commented on src/main/java/io/github/choising/team/Main.java
> +        System.out.println("자동차대수는몇대인가요?");
요구사항 그대로 반영하여 출력형식 적용함

2020-03-04 14:25 UTC, euigyu commented on src/main/java/io/github/choising/team/Main.java
> +        System.out.println("시도할횟수는몇회인가요?");
요구사항과 동일하게 출력형식 맞춤

2020-03-04 14:26 UTC, euigyu commented on src/main/java/io/github/choising/team/Main.java
> +                int randomValue = (int) (Math.random() * 9);
(int) (Math.random() * 10) 으로 0~9까지 나오게 적용

2020-03-04 14:28 UTC, euigyu commented on src/main/java/io/github/choising/team/Main.java
>  public class Main {
추가적으로 클래스 객체 만들어 보라고해서 CarRace클래스에 race메소드 구현, CarRace객체를 생성하고 CarRace의 race메소드를 통해 결과가 나오게끔 적용해씀

2020-03-05 15:24 UTC, Oraindrop approved these changes
👍

2020-03-05 15:24 UTC, merged